In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [13]:
voc_size=10000

In [14]:
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[8355, 1805, 4953, 8207],
 [8355, 1805, 4953, 9157],
 [8355, 3678, 4953, 4861],
 [4710, 3495, 7414, 63, 3109],
 [4710, 3495, 7414, 63, 8508],
 [1608, 8355, 6396, 4953, 2475],
 [9709, 9503, 2383, 63]]

In [10]:
## Word Embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [23]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8355 1805 4953 8207]
 [   0    0    0    0 8355 1805 4953 9157]
 [   0    0    0    0 8355 3678 4953 4861]
 [   0    0    0 4710 3495 7414   63 3109]
 [   0    0    0 4710 3495 7414   63 8508]
 [   0    0    0 1608 8355 6396 4953 2475]
 [   0    0    0    0 9709 9503 2383   63]]


In [18]:
#Feature Representation
dim=10

In [24]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\dell\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [26]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step


array([[[ 8.44489783e-04, -1.74614675e-02, -2.19460260e-02,
          4.99006025e-02, -1.87037364e-02,  8.04916769e-03,
         -1.72230601e-02,  2.92328633e-02, -1.66711956e-03,
         -4.29085381e-02],
        [ 8.44489783e-04, -1.74614675e-02, -2.19460260e-02,
          4.99006025e-02, -1.87037364e-02,  8.04916769e-03,
         -1.72230601e-02,  2.92328633e-02, -1.66711956e-03,
         -4.29085381e-02],
        [ 8.44489783e-04, -1.74614675e-02, -2.19460260e-02,
          4.99006025e-02, -1.87037364e-02,  8.04916769e-03,
         -1.72230601e-02,  2.92328633e-02, -1.66711956e-03,
         -4.29085381e-02],
        [ 8.44489783e-04, -1.74614675e-02, -2.19460260e-02,
          4.99006025e-02, -1.87037364e-02,  8.04916769e-03,
         -1.72230601e-02,  2.92328633e-02, -1.66711956e-03,
         -4.29085381e-02],
        [-1.23018026e-03,  3.16573046e-02,  2.65982859e-02,
          5.28769568e-03,  3.01250480e-02,  1.30442716e-02,
         -4.44722772e-02,  4.01882641e-02, -2.176239

In [30]:
embedded_docs[0]

array([   0,    0,    0,    0, 8355, 1805, 4953, 8207])

In [31]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>